openapi: 3.0.0
info:
  title: Sports betting
  version: 0.1.9
servers:
  - url: http://127.0.0.1:5000
    description: Optional server description, e.g. Main (production) server
  - url:  http://127.0.0.1:5000
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /user_register:
    post:
      description: Регистрирует пользователя с заданными данными.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInfo'
      responses:
        '200':
          description: Удачная попытка регистрации
        '400':
          description: Ошибка при валидации параметров (например, попытка повторной регистрации)
          schema:
            $ref: '#/components/schemas/ErrorResponse'

  /user_login:
    post:
      description: Залогинивает пользователя с заданными данными.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BaseUserInfo'
      responses:
        '200':
          description: Удачная попытка логина
        '400':
          description: Ошибка при валидации параметров
          schema:
            $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Пользователь не найден
          schema:
            $ref: '#/components/schemas/ErrorResponse'

  /user_register_approve:
    post:
      description: Подтверждает регистрацию пользователя (страница с вводом слова регистрации).
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterApprove'
      responses:
        '200':
          description: Удачное подтверждение
          schema:
            $ref: '#/components/schemas/UserInfo'
        '400':
          description: Ошибка при валидации параметров
          schema:
            $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Неверное кодовое слово
          schema:
            $ref: '#/components/schemas/ErrorResponse'

  /user:
    put:
      description: Изменение информации о пользователе.
      parameters:
        - in: query
          name: id
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserMeta'
      responses:
        '200':
          description: Удачное изменение
          schema:
            $ref: '#/components/schemas/UserInfo'
        '400':
          description: Ошибка при валидации параметров
          schema:
            $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Пользователь не найден
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    get:
      description: Выдача информации о пользователе
      parameters:
        - in: query
          name: id
          required: true
      responses:
        '200':
          schema:
            $ref: '#/components/schemas/UserInfo'
        '400':
          description: Ошибка при валидации параметров
          schema:
            $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Пользователь не найден
          schema:
            $ref: '#/components/schemas/ErrorResponse'

  /competitions:
    get:
      description: Получает все соревнования пользователя.
      parameters:
        - in: query
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          schema:
            type: object
            required:
              - competitions
            properties:
              competitions:
                type: array
                items:
                  $ref: '#/components/schemas/Competition'
        '400':
          description: Ошибка при валидации параметров
          schema:
            $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Пользователь не найден
          schema:
            $ref: '#/components/schemas/ErrorResponse'

  /competitions_info:
    post:
      description: Добавляет пользователя в участие в соревнование.
      parameters:
        - in: query
          name: competition_id
          required: true
          schema:
            type: string
        - in: query
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          schema:
            $ref: '#/components/schemas/Competition'
        '400':
          description: Ошибка при валидации параметров
          schema:
            $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Пользователь или соревнование не найдены
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    get:
      description: Отдает информаицю о соревновании для этого пользовтеля.
      parameters:
        - in: query
          name: competition_id
          required: true
          schema:
            type: string
        - in: query
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          schema:
            $ref: '#/components/schemas/Competition'
        '400':
          description: Ошибка при валидации параметров
          schema:
            $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Пользователь или соревнование не найдены
          schema:
            $ref: '#/components/schemas/ErrorResponse'

  /match_info:
    get:
      description: Отдает информаицю о матче для этого пользовтеля.
      parameters:
        - in: query
          name: match_id
          required: true
          schema:
            type: string
        - in: query
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          schema:
            $ref: '#/components/schemas/Match'
        '400':
          description: Ошибка при валидации параметров
          schema:
            $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Пользователь или соревнование не найдены
          schema:
            $ref: '#/components/schemas/ErrorResponse'

  /create/competition:
    post:
      description: Создает новое соревнование.
      parameters:
        - in: query
          name: id
          required: true
          schema:
            type: string
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              parsing_ref:
                type: string
            required:
              - parsing_ref
      responses:
        '200':
          schema:
            $ref: '#/components/schemas/Competition'
        '400':
          description: Ошибка при валидации параметров
          schema:
            $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Пользователь или соревнование не найдены
          schema:
            $ref: '#/components/schemas/ErrorResponse'

  /create/match:
    post:
      description: Создает новый матч.
      parameters:
        - in: query
          name: id
          required: true
          schema:
            type: string
        - in: query
          name: competion_id
          required: true
          schema:
            type: string
        - in: body
          name: parsing_ref
          required: true
          schema:
            type: string
      responses:
        '200':
          schema:
            $ref: '#/components/schemas/Match'
        '400':
          description: Ошибка при валидации параметров
          schema:
            $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Пользователь или соревнование не найдены
          schema:
            $ref: '#/components/schemas/ErrorResponse'

  /create/bet:
    post:
      description: Делает ставку.
      parameters:
        - in: query
          name: id
          required: true
          schema:
            type: string
        - in: query
          name: match_id
          required: true
          schema:
            type: string
        - in: body
          required: true
          name: body
          schema:
            type: object
            properties:
              bets:
                type: array
                items:
                  $ref: '#/components/schemas/Bets'
            required:
              - bets
      responses:
        '200':
          schema:
            $ref: '#/components/schemas/Match'
        '400':
          description: Ошибка при валидации параметров
          schema:
            $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Пользователь или соревнование не найдены
          schema:
            $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    UserMeta:
      type: object
      required:
        - password
      properties:
        name:
          type: string
        surname:
          type: string
        password:
          type: string

    UserInfo:
      type: object
      required:
        - user_meta
        - id
      properties:
        user_meta:
          $ref: '#/components/schemas/UserMeta'
        id:
          type: string

    BaseUserInfo:
      type: object
      required:
        - id
        - password
      properties:
        id:
          type: string
        password:
          type: string

    RegisterApprove:
      type: object
      required:
        - secret_code
        - id
      properties:
        id:
          type: string
        secret_code:
          type: string

    ErrorResponse:
      type: object
      required:
        - code
        - text
      properties:
        code:
          type: string
        text:
          type: string

    Match:
      type: object
      required:
        - id
        - name
        - first_team_result
        - second_team_result
        - first_team_name
        - second_team_name
      properties:
        id:
          type: integer
        name:
          type: string
        first_team_name:
          type: string
        second_team_name:
          type: string
        first_team_result:
          type: integer
        second_team_result:
          type: integer
        bets_result:
          type: double
        user_bets:
          type: array
          items:
            $ref: '#/components/schemas/Bets'

    Competition:
      type: object
      required:
        - name
        - id
        - is_active
        - matches
      properties:
        name:
          type: string
        id:
          type: integer
        is_active:
          type: boolean
        matches:
          type: array
          items:
            $ref: '#/components/schemas/Match'
        leader_board:
          type: array
          items:
            $ref: '#/components/schemas/BetsResult'

    Bets:
      type: object
      required:
        - name
        - bet
      properties:
        name:
          type: string
        bet:
          type: integer
        bet_profit:
          type: double

    BetsResult:
      type: object
      required:
        - user_id
        - result
      properties:
        user_id:
          type: string
        result:
          type: double
        bets:
          type: array
          items:
            $ref: '#/components/schemas/Bets'