version: "3"
services:
  authorization_server:
    image: annabogacheva/authorization_server
    network_mode: "host"
    environment:
      PASS_KEY: "${PASS_KEY}"
      TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN}"
      DB_USER: "${DB_USER}"
      DB_NAME: "${DB_NAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_HOST: "${DB_HOST}"

  sport_bet_bot:
    image: annabogacheva/sport_bet_bot
    network_mode: "host"
    environment:
      PASS_KEY: "${PASS_KEY}"
      TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN}"
      DB_USER: "${DB_USER}"
      DB_NAME: "${DB_NAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_HOST: "${DB_HOST}"

  sport_bet_server:
    image: annabogacheva/sport_bet_server
    network_mode: "host"
    environment:
      PASS_KEY: "${PASS_KEY}"
      TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN}"
      DB_USER: "${DB_USER}"
      DB_NAME: "${DB_NAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_HOST: "${DB_HOST}"