# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class CreateCompetitionBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, parsing_ref: str=None):  # noqa: E501
        """CreateCompetitionBody - a model defined in Swagger

        :param parsing_ref: The parsing_ref of this CreateCompetitionBody.  # noqa: E501
        :type parsing_ref: str
        """
        self.swagger_types = {
            'parsing_ref': str
        }

        self.attribute_map = {
            'parsing_ref': 'parsing_ref'
        }
        self._parsing_ref = parsing_ref

    @classmethod
    def from_dict(cls, dikt) -> 'CreateCompetitionBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The create_competition_body of this CreateCompetitionBody.  # noqa: E501
        :rtype: CreateCompetitionBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def parsing_ref(self) -> str:
        """Gets the parsing_ref of this CreateCompetitionBody.


        :return: The parsing_ref of this CreateCompetitionBody.
        :rtype: str
        """
        return self._parsing_ref

    @parsing_ref.setter
    def parsing_ref(self, parsing_ref: str):
        """Sets the parsing_ref of this CreateCompetitionBody.


        :param parsing_ref: The parsing_ref of this CreateCompetitionBody.
        :type parsing_ref: str
        """
        if parsing_ref is None:
            raise ValueError("Invalid value for `parsing_ref`, must not be `None`")  # noqa: E501

        self._parsing_ref = parsing_ref
