# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.bets import Bets  # noqa: F401,E501
from swagger_server import util


class CreateBetBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, bets: List[Bets]=None):  # noqa: E501
        """CreateBetBody - a model defined in Swagger

        :param bets: The bets of this CreateBetBody.  # noqa: E501
        :type bets: List[Bets]
        """
        self.swagger_types = {
            'bets': List[Bets]
        }

        self.attribute_map = {
            'bets': 'bets'
        }
        self._bets = bets

    @classmethod
    def from_dict(cls, dikt) -> 'CreateBetBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The create_bet_body of this CreateBetBody.  # noqa: E501
        :rtype: CreateBetBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def bets(self) -> List[Bets]:
        """Gets the bets of this CreateBetBody.


        :return: The bets of this CreateBetBody.
        :rtype: List[Bets]
        """
        return self._bets

    @bets.setter
    def bets(self, bets: List[Bets]):
        """Sets the bets of this CreateBetBody.


        :param bets: The bets of this CreateBetBody.
        :type bets: List[Bets]
        """
        if bets is None:
            raise ValueError("Invalid value for `bets`, must not be `None`")  # noqa: E501

        self._bets = bets
