# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.competition import Competition  # noqa: F401,E501
from swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, competitions: List[Competition]=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param competitions: The competitions of this InlineResponse200.  # noqa: E501
        :type competitions: List[Competition]
        """
        self.swagger_types = {
            'competitions': List[Competition]
        }

        self.attribute_map = {
            'competitions': 'competitions'
        }
        self._competitions = competitions

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def competitions(self) -> List[Competition]:
        """Gets the competitions of this InlineResponse200.


        :return: The competitions of this InlineResponse200.
        :rtype: List[Competition]
        """
        return self._competitions

    @competitions.setter
    def competitions(self, competitions: List[Competition]):
        """Sets the competitions of this InlineResponse200.


        :param competitions: The competitions of this InlineResponse200.
        :type competitions: List[Competition]
        """
        if competitions is None:
            raise ValueError("Invalid value for `competitions`, must not be `None`")  # noqa: E501

        self._competitions = competitions
