/*
 * Sports betting
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.9
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The BaseUserInfo model module.
 * @module model/BaseUserInfo
 * @version 0.1.9
 */
export class BaseUserInfo {
  /**
   * Constructs a new <code>BaseUserInfo</code>.
   * @alias module:model/BaseUserInfo
   * @class
   * @param id {String} 
   * @param password {String} 
   */
  constructor(id, password) {
    this.id = id;
    this.password = password;
  }

  /**
   * Constructs a <code>BaseUserInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BaseUserInfo} obj Optional instance to populate.
   * @return {module:model/BaseUserInfo} The populated <code>BaseUserInfo</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new BaseUserInfo();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('password'))
        obj.password = ApiClient.convertToType(data['password'], 'String');
      if (data.hasOwnProperty('token'))
        obj.token = ApiClient.convertToType(data['token'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
BaseUserInfo.prototype.id = undefined;

/**
 * @member {String} password
 */
BaseUserInfo.prototype.password = undefined;

/**
 * @member {String} token
 */
BaseUserInfo.prototype.token = undefined;

