/*
 * Sports betting
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.9
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Bets} from './Bets';

/**
 * The BetsResult model module.
 * @module model/BetsResult
 * @version 0.1.9
 */
export class BetsResult {
  /**
   * Constructs a new <code>BetsResult</code>.
   * @alias module:model/BetsResult
   * @class
   * @param userId {String} 
   * @param result {Number} 
   */
  constructor(userId, result) {
    this.userId = userId;
    this.result = result;
  }

  /**
   * Constructs a <code>BetsResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BetsResult} obj Optional instance to populate.
   * @return {module:model/BetsResult} The populated <code>BetsResult</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new BetsResult();
      if (data.hasOwnProperty('user_id'))
        obj.userId = ApiClient.convertToType(data['user_id'], 'String');
      if (data.hasOwnProperty('result'))
        obj.result = ApiClient.convertToType(data['result'], 'Number');
      if (data.hasOwnProperty('bets'))
        obj.bets = ApiClient.convertToType(data['bets'], [Bets]);
    }
    return obj;
  }
}

/**
 * @member {String} userId
 */
BetsResult.prototype.userId = undefined;

/**
 * @member {Number} result
 */
BetsResult.prototype.result = undefined;

/**
 * @member {Array.<module:model/Bets>} bets
 */
BetsResult.prototype.bets = undefined;

