/*
 * Sports betting
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.9
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Bets model module.
 * @module model/Bets
 * @version 0.1.9
 */
export class Bets {
  /**
   * Constructs a new <code>Bets</code>.
   * @alias module:model/Bets
   * @class
   * @param name {String} 
   * @param bet {Number} 
   */
  constructor(name, bet) {
    this.name = name;
    this.bet = bet;
  }

  /**
   * Constructs a <code>Bets</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Bets} obj Optional instance to populate.
   * @return {module:model/Bets} The populated <code>Bets</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Bets();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('bet'))
        obj.bet = ApiClient.convertToType(data['bet'], 'Number');
      if (data.hasOwnProperty('bet_profit'))
        obj.betProfit = ApiClient.convertToType(data['bet_profit'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
Bets.prototype.name = undefined;

/**
 * @member {Number} bet
 */
Bets.prototype.bet = undefined;

/**
 * @member {Number} betProfit
 */
Bets.prototype.betProfit = undefined;

