/*
 * Sports betting
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.9
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {BetsResult} from './BetsResult';
import {Match} from './Match';

/**
 * The Competition model module.
 * @module model/Competition
 * @version 0.1.9
 */
export class Competition {
  /**
   * Constructs a new <code>Competition</code>.
   * @alias module:model/Competition
   * @class
   * @param name {String} 
   * @param id {Number} 
   * @param isActive {Boolean} 
   * @param matches {Array.<module:model/Match>} 
   */
  constructor(name, id, isActive, matches) {
    this.name = name;
    this.id = id;
    this.isActive = isActive;
    this.matches = matches;
  }

  /**
   * Constructs a <code>Competition</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Competition} obj Optional instance to populate.
   * @return {module:model/Competition} The populated <code>Competition</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Competition();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('is_active'))
        obj.isActive = ApiClient.convertToType(data['is_active'], 'Boolean');
      if (data.hasOwnProperty('matches'))
        obj.matches = ApiClient.convertToType(data['matches'], [Match]);
      if (data.hasOwnProperty('leader_board'))
        obj.leaderBoard = ApiClient.convertToType(data['leader_board'], [BetsResult]);
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
Competition.prototype.name = undefined;

/**
 * @member {Number} id
 */
Competition.prototype.id = undefined;

/**
 * @member {Boolean} isActive
 */
Competition.prototype.isActive = undefined;

/**
 * @member {Array.<module:model/Match>} matches
 */
Competition.prototype.matches = undefined;

/**
 * @member {Array.<module:model/BetsResult>} leaderBoard
 */
Competition.prototype.leaderBoard = undefined;

