/*
 * Sports betting
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.9
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Bets} from './Bets';

/**
 * The CreateBetBody model module.
 * @module model/CreateBetBody
 * @version 0.1.9
 */
export class CreateBetBody {
  /**
   * Constructs a new <code>CreateBetBody</code>.
   * @alias module:model/CreateBetBody
   * @class
   * @param bets {Array.<module:model/Bets>} 
   */
  constructor(bets) {
    this.bets = bets;
  }

  /**
   * Constructs a <code>CreateBetBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateBetBody} obj Optional instance to populate.
   * @return {module:model/CreateBetBody} The populated <code>CreateBetBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CreateBetBody();
      if (data.hasOwnProperty('bets'))
        obj.bets = ApiClient.convertToType(data['bets'], [Bets]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/Bets>} bets
 */
CreateBetBody.prototype.bets = undefined;

