/*
 * Sports betting
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.9
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Bets} from './Bets';

/**
 * The Match model module.
 * @module model/Match
 * @version 0.1.9
 */
export class Match {
  /**
   * Constructs a new <code>Match</code>.
   * @alias module:model/Match
   * @class
   * @param id {Number} 
   * @param name {String} 
   * @param firstTeamName {String} 
   * @param secondTeamName {String} 
   * @param isActive {Boolean} 
   */
  constructor(id, name, firstTeamName, secondTeamName, isActive) {
    this.id = id;
    this.name = name;
    this.firstTeamName = firstTeamName;
    this.secondTeamName = secondTeamName;
    this.isActive = isActive;
  }

  /**
   * Constructs a <code>Match</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Match} obj Optional instance to populate.
   * @return {module:model/Match} The populated <code>Match</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Match();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('first_team_name'))
        obj.firstTeamName = ApiClient.convertToType(data['first_team_name'], 'String');
      if (data.hasOwnProperty('second_team_name'))
        obj.secondTeamName = ApiClient.convertToType(data['second_team_name'], 'String');
      if (data.hasOwnProperty('first_team_result'))
        obj.firstTeamResult = ApiClient.convertToType(data['first_team_result'], 'Number');
      if (data.hasOwnProperty('second_team_result'))
        obj.secondTeamResult = ApiClient.convertToType(data['second_team_result'], 'Number');
      if (data.hasOwnProperty('is_active'))
        obj.isActive = ApiClient.convertToType(data['is_active'], 'Boolean');
      if (data.hasOwnProperty('bets_result'))
        obj.betsResult = ApiClient.convertToType(data['bets_result'], 'Number');
      if (data.hasOwnProperty('user_bets'))
        obj.userBets = ApiClient.convertToType(data['user_bets'], [Bets]);
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
Match.prototype.id = undefined;

/**
 * @member {String} name
 */
Match.prototype.name = undefined;

/**
 * @member {String} firstTeamName
 */
Match.prototype.firstTeamName = undefined;

/**
 * @member {String} secondTeamName
 */
Match.prototype.secondTeamName = undefined;

/**
 * @member {Number} firstTeamResult
 */
Match.prototype.firstTeamResult = undefined;

/**
 * @member {Number} secondTeamResult
 */
Match.prototype.secondTeamResult = undefined;

/**
 * @member {Boolean} isActive
 */
Match.prototype.isActive = undefined;

/**
 * @member {Number} betsResult
 */
Match.prototype.betsResult = undefined;

/**
 * @member {Array.<module:model/Bets>} userBets
 */
Match.prototype.userBets = undefined;

