/*
 * Sports betting
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.9
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The RegisterApprove model module.
 * @module model/RegisterApprove
 * @version 0.1.9
 */
export class RegisterApprove {
  /**
   * Constructs a new <code>RegisterApprove</code>.
   * @alias module:model/RegisterApprove
   * @class
   * @param id {String} 
   * @param secretCode {String} 
   */
  constructor(id, secretCode) {
    this.id = id;
    this.secretCode = secretCode;
  }

  /**
   * Constructs a <code>RegisterApprove</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RegisterApprove} obj Optional instance to populate.
   * @return {module:model/RegisterApprove} The populated <code>RegisterApprove</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RegisterApprove();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('secret_code'))
        obj.secretCode = ApiClient.convertToType(data['secret_code'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
RegisterApprove.prototype.id = undefined;

/**
 * @member {String} secretCode
 */
RegisterApprove.prototype.secretCode = undefined;

