/*
 * Sports betting
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.9
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The UserMeta model module.
 * @module model/UserMeta
 * @version 0.1.9
 */
export class UserMeta {
  /**
   * Constructs a new <code>UserMeta</code>.
   * @alias module:model/UserMeta
   * @class
   * @param password {String} 
   */
  constructor(password) {
    this.password = password;
  }

  /**
   * Constructs a <code>UserMeta</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserMeta} obj Optional instance to populate.
   * @return {module:model/UserMeta} The populated <code>UserMeta</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UserMeta();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('surname'))
        obj.surname = ApiClient.convertToType(data['surname'], 'String');
      if (data.hasOwnProperty('password'))
        obj.password = ApiClient.convertToType(data['password'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
UserMeta.prototype.name = undefined;

/**
 * @member {String} surname
 */
UserMeta.prototype.surname = undefined;

/**
 * @member {String} password
 */
UserMeta.prototype.password = undefined;

