/*
 * Sports betting
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.9
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {UserMeta} from './UserMeta';

/**
 * The UserInfo model module.
 * @module model/UserInfo
 * @version 0.1.9
 */
export class UserInfo {
  /**
   * Constructs a new <code>UserInfo</code>.
   * @alias module:model/UserInfo
   * @class
   * @param userMeta {module:model/UserMeta} 
   * @param id {String} 
   */
  constructor(userMeta, id) {
    this.userMeta = userMeta;
    this.id = id;
  }

  /**
   * Constructs a <code>UserInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserInfo} obj Optional instance to populate.
   * @return {module:model/UserInfo} The populated <code>UserInfo</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UserInfo();
      if (data.hasOwnProperty('user_meta'))
        obj.userMeta = UserMeta.constructFromObject(data['user_meta']);
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
    }
    return obj;
  }
}

/**
 * @member {module:model/UserMeta} userMeta
 */
UserInfo.prototype.userMeta = undefined;

/**
 * @member {String} id
 */
UserInfo.prototype.id = undefined;

