/*
 * Sports betting
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.9
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SportsBetting);
  }
}(this, function(expect, SportsBetting) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Bets', function() {
      beforeEach(function() {
        instance = new SportsBetting.Bets();
      });

      it('should create an instance of Bets', function() {
        // TODO: update the code to test Bets
        expect(instance).to.be.a(SportsBetting.Bets);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property bet (base name: "bet")', function() {
        // TODO: update the code to test the property bet
        expect(instance).to.have.property('bet');
        // expect(instance.bet).to.be(expectedValueLiteral);
      });

      it('should have the property betProfit (base name: "bet_profit")', function() {
        // TODO: update the code to test the property betProfit
        expect(instance).to.have.property('betProfit');
        // expect(instance.betProfit).to.be(expectedValueLiteral);
      });

    });
  });

}));
