/*
 * Sports betting
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.9
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SportsBetting);
  }
}(this, function(expect, SportsBetting) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Competition', function() {
      beforeEach(function() {
        instance = new SportsBetting.Competition();
      });

      it('should create an instance of Competition', function() {
        // TODO: update the code to test Competition
        expect(instance).to.be.a(SportsBetting.Competition);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property isActive (base name: "is_active")', function() {
        // TODO: update the code to test the property isActive
        expect(instance).to.have.property('isActive');
        // expect(instance.isActive).to.be(expectedValueLiteral);
      });

      it('should have the property matches (base name: "matches")', function() {
        // TODO: update the code to test the property matches
        expect(instance).to.have.property('matches');
        // expect(instance.matches).to.be(expectedValueLiteral);
      });

      it('should have the property leaderBoard (base name: "leader_board")', function() {
        // TODO: update the code to test the property leaderBoard
        expect(instance).to.have.property('leaderBoard');
        // expect(instance.leaderBoard).to.be(expectedValueLiteral);
      });

    });
  });

}));
