/*
 * Sports betting
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.9
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SportsBetting);
  }
}(this, function(expect, SportsBetting) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('RegisterApprove', function() {
      beforeEach(function() {
        instance = new SportsBetting.RegisterApprove();
      });

      it('should create an instance of RegisterApprove', function() {
        // TODO: update the code to test RegisterApprove
        expect(instance).to.be.a(SportsBetting.RegisterApprove);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property secretCode (base name: "secret_code")', function() {
        // TODO: update the code to test the property secretCode
        expect(instance).to.have.property('secretCode');
        // expect(instance.secretCode).to.be(expectedValueLiteral);
      });

    });
  });

}));
